dist: xenial
language: go
sudo: true
go:
  - 1.9.2

services:
  - docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.9.4/bin/darwin/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -Lo minikube.bin https://storage.googleapis.com/minikube/releases/v0.26.0/minikube-linux-amd64
  - sudo chmod +x minikube.bin
  - sudo mv minikube.bin /usr/local/bin/minikube
  - sudo minikube start --v=999 --logtostderr --vm-driver=none --kubernetes-version=v1.9.4
  #- sudo minikube start --v=10 --logtostderr --vm-driver=none --kubernetes-version=v1.9.4 --extra-config=apiserver.Authorization.Mode=RBAC
  - minikube update-context
  # Wait for Kubernetes to be up and ready.
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

script:
  - kubectl cluster-info
#  - go get -t -v ./...

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
