apiVersion: v1
kind: Pod
metadata:
  name: busybox-recover
  namespace: default
spec:
  containers:
  - command:
       - sh
       - -c
       - 'while true; do cat /mnt/store1/date.txt; sleep 5; done;'
    image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /mnt/store1
      name: demo-vol1
  volumes:
  - name: demo-vol1
    persistentVolumeClaim:
      claimName: demo-vol1-recover-claim
