---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-recover-claim
spec:
  storageClassName: openebs-standalone
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
