---
apiVersion: v1
kind: Pod
metadata:
  name: tests-fio
  labels:
    name: tests-fio
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: tests-fio
    image: openebs/tests-fio
    command: ["/fio_runner.sh"]
    args: ["Basic", "60"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: demo-vol1
  volumes:
    - name: demo-vol1
      persistentVolumeClaim:
        claimName: demo-vol1-claim 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol1-claim
spec:
  storageClassName: openebs-mount
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2G"
 
