kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbgcstor-claim
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: VolumeTargetImage
        value: "openebs/cstor-istgt-ci:highcpu-0.8.0-2-g18434e2"
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4G"
