apiVersion: v1
kind: Pod
metadata:
  name: fio-dbgcstor
  labels:
    name: fio-dbgcstor
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: fio-dbgcstor
    image: openebs/tests-fio
    command: ["/bin/bash"]
    args: ["-c", "./fio_runner.sh --template file/basic-rw --size 256m --duration 300; exit 0"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: fio-dbgcstor-claim 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-dbgcstor-claim
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: VolumeTargetImage
        value: "ivishnuvardhan/cstor-istgt:highcpuv1"
spec:
  storageClassName: openebs-cstor-sparse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4G"
