apiVersion: v1
kind: Pod
metadata:
  name: fio-jiva-1r
  labels:
    name: fio-jiva
spec:
  containers:
  - resources:
      limits:
        cpu: 0.5
    name: fio-jiva
    image: openebs/tests-fio
    command: ["/bin/bash"]
    args: ["-c", "./fio_runner.sh --template file/basic-rw --size 256m --duration 300; exit 0"]
    tty: true
    volumeMounts:
    - mountPath: /datadir
      name: datavol
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: fio-jiva-1r-claim 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-jiva-1r-claim
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "1"
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4G"
