---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jiva-retain
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Retain
---
