kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-vol
  namespace: test
spec:
  storageClassName: openebs-percona
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G

