---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-gpd
  annotations:
    openebs.io/cas-type: jiva
    cas.openebs.io/config: |
      - name: "StoragePool"
        value: "jiva-gpd-pool"
provisioner: openebs.io/provisioner-iscsi
