apiVersion: v1
kind: Pod
metadata:
  name: bb-node-affinity-with-matchfields
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - gke-kmova-helm-default-pool-20ff78e2-5dv4
  containers:
  - name: busybox
    image: busybox
